/**
 * ─── useFileSync ──────────────────────────────────────────────────────────────
 * Syncs the Vectra element tree to the WebContainer VFS.
 *
 * PHASE E: Framework Switcher
 * ────────────────────────────
 * All VFS paths and code generators now branch on `framework` from useProject().
 * The two supported frameworks produce entirely different file structures:
 *
 *   NEXT.JS (framework === 'nextjs')
 *   ─────────────────────────────────────────────────────────────────────────
 *   components/[Name].tsx        custom_code component files
 *   app/page.tsx                 Home page
 *   app/[slug]/page.tsx          Additional pages
 *   app/layout.tsx               Root layout (with Navbar if 2+ pages)
 *   components/Navbar.tsx        Multi-page navigation
 *   app/api/[path]/route.ts      API routes (Phase D, framework-agnostic)
 *   data/project.json            Serialized project for ZIP
 *   tailwind-gen.js              JIT ghost file (root)
 *   tailwind.config.js           Next.js content paths
 *
 *   VITE (framework === 'vite')
 *   ─────────────────────────────────────────────────────────────────────────
 *   src/components/[Name].tsx    custom_code component files
 *   src/App.tsx                  BrowserRouter + Routes (all pages)
 *   src/data/project.json        Serialized project for ZIP
 *   src/tailwind-gen.js          JIT ghost file (src/)
 *   tailwind.config.js           Vite content paths
 *
 * PRESERVED FROM PRIOR PHASES:
 *   • Phase 4: All dirty-check guards (ref equality, drag suppression,
 *              concurrency, debounce, per-file content guard)
 *   • Phase C: buildTailwindConfig(), toPascalCase(), wrapWithImports()
 *   • Phase D: Section F (API routes), prevApiRoutesRef
 */

import { useEffect, useRef } from 'react';
import { useProject } from '../context/ProjectContext';
import { useUI } from '../context/UIContext';
import { useContainer } from '../context/ContainerContext';
import {
  generateNextPage,
  generateRootLayout,
  generateNextNavbar,
  slugToNextPath,
  generateApiRouteFile,
  apiRouteToVfsPath,
  generateProjectCode,
  deduplicatePageSlugs,
} from '../utils/codegen/codeGenerator';
import type { VectraProject } from '../types';

// ─── HELPERS ──────────────────────────────────────────────────────────────────

/**
 * PascalCase converter — mirrors generateNextPage() exactly.
 * MUST NOT diverge — component file names must match import paths.
 */
const toPascalCase = (raw: string): string => {
  const cleaned = raw
    .replace(/[^a-zA-Z0-9\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
  return /^[A-Z]/.test(cleaned) ? cleaned : 'Component' + cleaned;
};

/**
 * wrapWithImports — Next.js variant
 * 'use client' is the first line (required for App Router).
 */
const wrapWithImportsNext = (rawCode: string): string =>
  `'use client';

import React, { useState, useEffect, useRef } from 'react';
import * as Lucide from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { cn } from '@/lib/utils';

/* ─── Auto-generated by Vectra AI ─────────────────────────────────────────── */
${rawCode}
`;

/**
 * wrapWithImports — Vite variant
 * No 'use client'. Path is '../lib/utils' (src/components/ is 2 levels deep).
 */
const wrapWithImportsVite = (rawCode: string): string =>
  `import React, { useState, useEffect, useRef } from 'react';
import * as Lucide from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { cn } from '../lib/utils';

/* ─── Auto-generated by Vectra AI ─────────────────────────────────────────── */
${rawCode}
`;

/**
 * buildViteAppTsx
 * ────────────────
 * Generates src/App.tsx content for the Vite/React Router output.
 */
const buildViteAppTsx = (
  elements: VectraProject,
  pages: Array<{ id: string; name: string; slug: string; rootId: string }>
): string => {
  const customEls = Object.values(elements).filter(
    el => el.type === 'custom_code' && typeof el.code === 'string' && el.code.trim().length > 0
  );

  const componentImports = customEls.map(el => {
    const name = toPascalCase(el.name?.trim() || el.id);
    return `import ${name} from './components/${name}';`;
  }).join('\n');

  const pageImports = pages.map(p => {
    const name = p.name.replace(/[^a-zA-Z0-9]/g, '') || 'Home';
    return `import ${name}Page from './pages/${name}Page';`;
  }).join('\n');

  const routes = pages.map(p => {
    const name = p.name.replace(/[^a-zA-Z0-9]/g, '') || 'Home';
    return `        <Route path="${p.slug}" element={<${name}Page />} />`;
  }).join('\n');

  return `import React from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
${pageImports}
${componentImports}

export default function App() {
  return (
    <BrowserRouter>
      <Routes>
${routes}
      </Routes>
    </BrowserRouter>
  );
}
`;
};

/**
 * buildNextTailwindConfig — Next.js version
 */
const buildNextTailwindConfig = (theme: {
  primary: string; secondary: string; accent: string; radius: string; font: string;
}): string =>
  `/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './tailwind-gen.js',
    './data/project.json',
  ],
  theme: {
    extend: {
      colors: { primary: '${theme.primary}', secondary: '${theme.secondary}', accent: '${theme.accent}' },
      borderRadius: { DEFAULT: '${theme.radius}' },
      fontFamily: { sans: ['${theme.font}', 'sans-serif'] },
    },
  },
  plugins: [],
}`;

/**
 * buildViteTailwindConfig — Vite version
 */
const buildViteTailwindConfig = (theme: {
  primary: string; secondary: string; accent: string; radius: string; font: string;
}): string =>
  `/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    './src/tailwind-gen.js',
    './src/data/project.json',
  ],
  theme: {
    extend: {
      colors: { primary: '${theme.primary}', secondary: '${theme.secondary}', accent: '${theme.accent}' },
      borderRadius: { DEFAULT: '${theme.radius}' },
      fontFamily: { sans: ['${theme.font}', 'sans-serif'] },
    },
  },
  plugins: [],
}`;

// ─── HOOK ─────────────────────────────────────────────────────────────────────

export const useFileSync = () => {
  const { elements, pages, theme, apiRoutes, dataSources, framework } = useProject();
  const { interaction } = useUI();
  const { writeFile, removeFile, status, instance } = useContainer();

  // ── Dirty-check refs ──────────────────────────────────────────────────────
  const prevElementsRef = useRef<VectraProject>({});
  const prevPageStructuresRef = useRef<Record<string, string>>({});
  const prevThemeKeyRef = useRef<string>('');
  const prevClassesRef = useRef<string>('');
  const prevPageCountRef = useRef<number>(0);
  // Phase D: API route dirty-check. Value format: "updatedAt::vfsPath"
  const prevApiRoutesRef = useRef<Record<string, string>>({});
  // DB-1: Data source dirty-check ref (JSON of stable fields)
  const prevDataSourcesRef = useRef<string>('');

  // VFS-STALE-1: tracks id → PascalName for every custom_code node written to VFS.
  // When a node is renamed, the old file path is computed from the previous name
  // and deleted before the new one is written. Without this, renaming Navbar to
  // NavbarV2 leaves components/Navbar.tsx on disk indefinitely.
  const prevCodeNodeNamesRef = useRef<Map<string, string>>(new Map());

  const syncedFiles = useRef<Map<string, string>>(new Map());
  const isSyncing = useRef<boolean>(false);

  // PERF-3 [PERMANENT]: AI generation starvation guard.
  //
  // PROBLEM: AI calls setElements many times while building a page. Each call
  // resets the 800ms debounce (nodeCountChanged = true). If AI fires setElements
  // every ~200ms over 3 seconds, the VFS never receives a write — the timer is
  // perpetually evicted before it can fire.
  //
  // FIX: isAIRunning ref gates debounce to 1000ms while generation is active.
  // syncForcedAfterAI ref ensures exactly ONE sync fires when AI finishes,
  // even if no further element change occurs.
  //
  // WIRING: ProjectContext sets window.__vectra_ai_running = true/false around
  // runAI(). This hook reads it via the ref — zero re-render cost.
  const isAIRunning = useRef<boolean>(false);
  const syncForcedAfterAI = useRef<boolean>(false);

  // NS-7 FIX: interaction in the dep array caused the sync effect to re-run at 60fps
  // during drag (setInteraction produces a new object every pointermove). The early-return
  // guard was hit correctly but the debounce timer was still reset 60×/second, starving
  // the VFS for the entire drag duration (> 800ms). Now use a ref mirrored by a separate
  // stable effect, and remove interaction from the sync dep array entirely.
  const interactionRef = useRef(interaction);
  useEffect(() => { interactionRef.current = interaction; }, [interaction]);

  useEffect(() => {
    // ── Guard 1: VFS not ready ────────────────────────────────────────────
    if (status !== 'ready' || !instance) return;

    // ── Guard 2: Suppress during 60fps drag/resize (NS-7: reads ref, not dep) ────
    if (interactionRef.current?.type === 'MOVE' || interactionRef.current?.type === 'RESIZE') return;

    // ── Guard 3: Early-exit if nothing changed ────────────────────────────
    if (elements === prevElementsRef.current && pages.length === prevPageCountRef.current) return;

    const sync = async () => {
      if (isSyncing.current) return;
      isSyncing.current = true;
      // UX-28 [PERMANENT]: Notify Header that a VFS write cycle is starting.
      // Event is tiny (no payload serialization cost) — safe at sync frequency.
      window.dispatchEvent(new CustomEvent('vectra:save-state', { detail: { saving: true } }));

      // ── Resolve framework-specific path constants ─────────────────────
      const isNext = framework === 'nextjs';
      const componentDir = isNext ? 'components' : 'src/components';
      const projectJsonPath = isNext ? 'data/project.json' : 'src/data/project.json';
      const tailwindGenPath = isNext ? 'tailwind-gen.js' : 'src/tailwind-gen.js';

      try {
        const prevElements = prevElementsRef.current;

        // ════════════════════════════════════════════════════════════════
        // SECTION A — COMPONENT FILES
        // custom_code nodes → [componentDir]/[ComponentName].tsx
        // ════════════════════════════════════════════════════════════════
        // H-3 FIX: the previous 2-level manual loop reached only:
        //   page-root → webpage/canvas → direct children
        // Any custom_code node nested inside a container, section, card, etc.
        // was never added to allChildIds — its file was never written to VFS.
        // At dev-server start Next.js throws `Module not found` with no editor error.
        // Replace with a proper recursive walk over the full page subtree.
        const allChildIds = new Set<string>();
        const walkNode = (id: string) => {
          if (allChildIds.has(id)) return; // cycle-guard
          allChildIds.add(id);
          (elements[id]?.children || []).forEach(walkNode);
        };
        for (const page of pages) {
          walkNode(page.rootId);
        }

        for (const nodeId of allChildIds) {
          const currentNode = elements[nodeId];
          const prevNode = prevElements[nodeId];
          if (currentNode === prevNode) continue;

          if (
            currentNode?.type === 'custom_code' &&
            typeof currentNode.code === 'string' &&
            currentNode.code.trim().length > 0
          ) {
            const componentName = toPascalCase(currentNode.name?.trim() || currentNode.id);
            const filePath = `${componentDir}/${componentName}.tsx`;

            // VFS-STALE-1 FIX: detect renames and evict the old file.
            // If this node existed before under a DIFFERENT PascalName,
            // the old file is now orphaned on disk. Remove it first.
            const prevName = prevCodeNodeNamesRef.current.get(nodeId);
            if (prevName && prevName !== componentName) {
              const stalePath = `${componentDir}/${prevName}.tsx`;
              try {
                await removeFile(stalePath);
                syncedFiles.current.delete(stalePath);
                console.log(`🗑️ [Vectra] Stale component evicted → ${stalePath}`);
              } catch {
                // File may not exist yet — safe to ignore
              }
            }
            // Update name tracking regardless of dirty-check below.
            prevCodeNodeNamesRef.current.set(nodeId, componentName);

            const content = isNext
              ? wrapWithImportsNext(currentNode.code)
              : wrapWithImportsVite(currentNode.code);

            if (syncedFiles.current.get(filePath) !== content) {
              await writeFile(filePath, content);
              syncedFiles.current.set(filePath, content);
              console.log(`📦 [Vectra] Component → ${filePath}`);
            }
          }

          // VFS-STALE-1: handle deletion — node was custom_code, now gone or type-changed.
          if (
            prevNode?.type === 'custom_code' &&
            (currentNode === undefined || currentNode?.type !== 'custom_code')
          ) {
            const prevName = prevCodeNodeNamesRef.current.get(nodeId);
            if (prevName) {
              const stalePath = `${componentDir}/${prevName}.tsx`;
              try {
                await removeFile(stalePath);
                syncedFiles.current.delete(stalePath);
                console.log(`🗑️ [Vectra] Deleted component evicted → ${stalePath}`);
              } catch { /* already gone — safe */ }
              prevCodeNodeNamesRef.current.delete(nodeId);
            }
          }
        }

        // ════════════════════════════════════════════════════════════════
        // SECTION B — PAGE / APP FILES
        //
        // NEXT.JS: Per-page app/[slug]/page.tsx + app/layout.tsx
        // VITE:    Single src/App.tsx with BrowserRouter + Routes
        // ════════════════════════════════════════════════════════════════
        let anyPageChanged = false;

        if (isNext) {
          // ── B-NEXT: Per-page generation ───────────────────────────
          const safePages = deduplicatePageSlugs(pages);
          const currentSafePageIds = new Set(safePages.map(p => p.id));

          // Detect + remove deleted pages and detect renames
          for (const [prevId, prevEntry] of Object.entries(prevPageStructuresRef.current)) {
            if (prevId === '__vite_pages__') continue;

            const prevPath = prevEntry.split('::')[0];
            const correspondingSafePage = safePages.find(p => p.id === prevId);
            const currentPath = correspondingSafePage ? slugToNextPath(correspondingSafePage.slug) : null;

            // If the page was deleted OR renamed (path changed), remove the old file
            if (!currentSafePageIds.has(prevId) || (currentPath && prevPath !== currentPath)) {
              if (prevPath && prevPath !== 'app/page.tsx' && prevPath !== 'src/App.tsx') {
                try {
                  await removeFile(prevPath);
                  syncedFiles.current.delete(prevPath);
                  console.log(`🗑️ [Vectra] Deleted page file → ${prevPath}`);
                } catch {
                  // File may not exist yet
                }
              }
              if (!currentSafePageIds.has(prevId)) {
                delete prevPageStructuresRef.current[prevId];
              }
            }
          }

          for (const page of safePages) {
            // H-1 FIX: the previous structureKey used Object.keys(props).length
            // per direct child — a count that never changes on text edits, style
            // value changes, src changes, or mutations to nested nodes.
            // Result: page file was never re-synced for the most common editor ops.
            //
            // Replacement: recursive subtree walk accumulating id + full node JSON.
            // elements is replaced immutably on every edit, so any descendant change
            // produces a new object ref → new JSON.stringify → different structureKey.
            // Cost: JSON.stringify is O(subtree) but paid once per changed page per
            // 1s debounce tick — never on the 60fps hot path.
            const collectSubtreeForKey = (id: string, out: string[]) => {
              const node = elements[id];
              if (!node) return;
              out.push(`${id}:${JSON.stringify(node)}`);
              (node.children || []).forEach(cid => collectSubtreeForKey(cid, out));
            };
            const subtreeFragments: string[] = [];
            collectSubtreeForKey(page.rootId, subtreeFragments);
            const structureKey = subtreeFragments.join('|');

            const filePath = slugToNextPath(page.slug);
            const prevEntry = prevPageStructuresRef.current[page.id];
            const prevStructure = prevEntry?.split('::')[1];

            // Same path and same structure -> skip
            if (prevEntry && prevEntry.startsWith(filePath + '::') && prevStructure === structureKey) {
              continue;
            }

            anyPageChanged = true;
            let pageContent: string;
            try {
              pageContent = generateNextPage(page, elements);
            } catch {
              pageContent = `export default function ${page.name.replace(/\s/g, '')}Page() { return <main className="p-8">Page Error</main>; }`;
            }

            if (syncedFiles.current.get(filePath) !== pageContent) {
              await writeFile(filePath, pageContent);
              syncedFiles.current.set(filePath, pageContent);
              console.log(`📄 [Vectra] Page → ${filePath}`);
            }
            prevPageStructuresRef.current[page.id] = `${filePath}::${structureKey}`;
          }

          // ── B-NEXT: layout.tsx + Navbar ───────────────────────────
          const pageCountChanged = safePages.length !== prevPageCountRef.current;
          if (pageCountChanged || anyPageChanged) {
            const layoutContent = generateRootLayout(safePages, theme);
            if (syncedFiles.current.get('app/layout.tsx') !== layoutContent) {
              await writeFile('app/layout.tsx', layoutContent);
              syncedFiles.current.set('app/layout.tsx', layoutContent);
              console.log('[Vectra] Layout → app/layout.tsx');
            }
            if (safePages.length > 1) {
              const navContent = generateNextNavbar(safePages);
              if (syncedFiles.current.get('components/Navbar.tsx') !== navContent) {
                await writeFile('components/Navbar.tsx', navContent);
                syncedFiles.current.set('components/Navbar.tsx', navContent);
                console.log('[Vectra] Navbar → components/Navbar.tsx');
              }
            }
          }

        } else {
          // ── B-VITE: Single App.tsx with BrowserRouter ──────────────
          const pagesKey = JSON.stringify(pages.map(p => p.id));
          const structureChanged = pagesKey !== (prevPageStructuresRef.current['__vite_pages__'] || '');

          if (structureChanged || pages.length !== prevPageCountRef.current) {
            anyPageChanged = true;

            // Generate page component files via Vite generator
            const { files: viteFiles } = generateProjectCode(elements, pages, []);
            for (const [filePath, content] of Object.entries(viteFiles)) {
              if (syncedFiles.current.get(filePath) !== content) {
                await writeFile(filePath, content);
                syncedFiles.current.set(filePath, content);
                console.log(`📄 [Vectra] Vite page → ${filePath}`);
              }
            }

            // Write the top-level App.tsx
            const appContent = buildViteAppTsx(elements, pages);
            if (syncedFiles.current.get('src/App.tsx') !== appContent) {
              await writeFile('src/App.tsx', appContent);
              syncedFiles.current.set('src/App.tsx', appContent);
              console.log('[Vectra] App → src/App.tsx');
            }

            prevPageStructuresRef.current['__vite_pages__'] = pagesKey;
          }
        }

        prevPageCountRef.current = pages.length;

        // ════════════════════════════════════════════════════════════════
        // SECTION C — PROJECT JSON
        // ════════════════════════════════════════════════════════════════
        const projectData = { pages, elements, framework };
        const jsonString = JSON.stringify(projectData, null, 2);
        if (syncedFiles.current.get(projectJsonPath) !== jsonString) {
          await writeFile(projectJsonPath, jsonString);
          syncedFiles.current.set(projectJsonPath, jsonString);
        }

        // ════════════════════════════════════════════════════════════════
        // SECTION D — TAILWIND GHOST CLASSES (JIT scanner)
        // ════════════════════════════════════════════════════════════════
        const canvasClasses = Object.values(elements)
          .map(el => (el.props as any)?.className || '').join(' ');
        const codeClasses = Object.values(elements)
          .filter(el => el.type === 'custom_code' && el.code)
          .map(el => el.code!).join(' ');
        const allClasses = `${canvasClasses} ${codeClasses}`.trim();

        if (allClasses !== prevClassesRef.current) {
          const ghostContent = `// Auto-generated for Tailwind JIT\nexport const classes = "${allClasses.replace(/"/g, "'")}";`;
          if (syncedFiles.current.get(tailwindGenPath) !== ghostContent) {
            await writeFile(tailwindGenPath, ghostContent);
            syncedFiles.current.set(tailwindGenPath, ghostContent);
          }
          prevClassesRef.current = allClasses;
        }

        // ════════════════════════════════════════════════════════════════
        // SECTION E — TAILWIND CONFIG + LAYOUT (theme changes)
        // ════════════════════════════════════════════════════════════════
        const themeKey = JSON.stringify(theme);
        if (themeKey !== prevThemeKeyRef.current) {
          const twContent = isNext
            ? buildNextTailwindConfig(theme)
            : buildViteTailwindConfig(theme);
          await writeFile('tailwind.config.js', twContent);

          if (isNext) {
            const layoutContent = generateRootLayout(pages, theme);
            await writeFile('app/layout.tsx', layoutContent);
            syncedFiles.current.set('app/layout.tsx', layoutContent);
          }

          prevThemeKeyRef.current = themeKey;
          console.log('[Vectra] Theme synced → tailwind.config.js');
        }

        // ════════════════════════════════════════════════════════════════
        // SECTION F — API ROUTE FILES (Phase D — framework-agnostic)
        // ════════════════════════════════════════════════════════════════
        {
          const currentRouteIds = new Set(apiRoutes.map(r => r.id));

          // Detect + remove deleted routes
          for (const [prevId, prevEntry] of Object.entries(prevApiRoutesRef.current)) {
            if (!currentRouteIds.has(prevId)) {
              const vfsPath = prevEntry.split('::')[1];
              if (vfsPath) {
                try {
                  await removeFile(vfsPath);
                  console.log(`🗑️ [Vectra] Deleted route → ${vfsPath}`);
                } catch {
                  // File may not exist yet — safe to ignore
                }
              }
              delete prevApiRoutesRef.current[prevId];
            }
          }

          // Write/update dirty routes
          for (const route of apiRoutes) {
            const prevEntry = prevApiRoutesRef.current[route.id];
            const prevUpdatedAt = prevEntry?.split('::')[0];
            if (prevUpdatedAt === route.updatedAt) continue;

            const vfsPath = apiRouteToVfsPath(route.path);
            const fileContent = generateApiRouteFile(route);
            if (syncedFiles.current.get(vfsPath) !== fileContent) {
              await writeFile(vfsPath, fileContent);
              syncedFiles.current.set(vfsPath, fileContent);
              console.log(`🛣️ [Vectra] API route → ${vfsPath}`);
            }
            prevApiRoutesRef.current[route.id] = `${route.updatedAt}::${vfsPath}`;
          }
        }

        // ════════════════════════════════════════════════════════════════
        // SECTION G — DATA SOURCES: .env.local + data/sources.ts (DB-1)
        // ════════════════════════════════════════════════════════════════
        {
          const dsKey = JSON.stringify(
            dataSources.map(ds => ({
              id: ds.id, url: ds.url, kind: ds.kind,
              envVarMap: ds.envVarMap,
              supabaseTable: ds.supabaseTable,
              psHost: ds.psHost, psDatabase: ds.psDatabase,
            }))
          );

          if (dsKey !== prevDataSourcesRef.current) {
            // ── Build .env.local ────────────────────────────────────────
            const envLines: string[] = [
              '# .env.local — auto-generated by Vectra Visual Builder',
              '# DO NOT COMMIT to Git. Add .env.local to .gitignore.',
              '',
            ];

            for (const ds of dataSources) {
              if (!ds.envVarMap || Object.keys(ds.envVarMap).length === 0) continue;
              envLines.push(`# ${ds.name} (${ds.kind ?? 'rest'})`);
              for (const [field, envKey] of Object.entries(ds.envVarMap)) {
                const value = (ds as any)[field] ?? '';
                envLines.push(`${envKey}=${value}`);
              }
              envLines.push('');
            }

            // DB-B FIX: Always write .env.local when dataSources change.
            // Previous guard `envLines.length > 3` skipped the write when the
            // last secret source was deleted — leaving stale credentials on disk.
            // Now we always write: either the populated file or an empty header.
            if (envLines.length > 3) {
              await writeFile('.env.local', envLines.join('\n'));
            } else {
              // All secret sources removed — clear stale credentials.
              await writeFile('.env.local', [
                '# .env.local — auto-generated by Vectra Visual Builder',
                '# DO NOT COMMIT to Git. Add .env.local to .gitignore.',
                '# No data sources with secrets are currently configured.',
              ].join('\n'));
            }

            // ── Build data/sources.ts ───────────────────────────────────
            const isNext = framework === 'nextjs';
            const sourcesPath = isNext ? 'data/sources.ts' : 'src/data/sources.ts';
            const srcLines: string[] = [
              '// data/sources.ts — auto-generated by Vectra. Do not edit.',
              '',
            ];

            for (const ds of dataSources) {
              const fnName = `fetch${ds.name.replace(/[^a-zA-Z0-9]/g, '_').replace(/^[^a-zA-Z]/, '_')}`;
              const kind = ds.kind ?? 'rest';
              if (kind === 'rest') {
                srcLines.push(
                  `export async function ${fnName}() {`,
                  `  const res = await fetch(${JSON.stringify(ds.url)}, { method: ${JSON.stringify(ds.method)} });`,
                  `  if (!res.ok) throw new Error(\`${ds.name}: \${res.status}\`);`,
                  `  return res.json();`,
                  `}`, '',
                );
              } else if (kind === 'supabase') {
                const urlVar = ds.envVarMap?.url ?? 'NEXT_PUBLIC_SUPABASE_URL';
                const keyVar = ds.envVarMap?.supabaseAnonKey ?? 'NEXT_PUBLIC_SUPABASE_ANON_KEY';
                srcLines.push(
                  `export async function ${fnName}() {`,
                  `  const url = process.env.${urlVar};`,
                  `  const key = process.env.${keyVar};`,
                  `  const res = await fetch(\`\${url}/rest/v1/${ds.supabaseTable ?? ''}\`, {`,
                  `    headers: { apikey: key!, Authorization: \`Bearer \${key}\` },`,
                  `  });`,
                  `  if (!res.ok) throw new Error(\`${ds.name}: \${res.status}\`);`,
                  `  return res.json();`,
                  `}`, '',
                );
              } else if (kind === 'planetscale') {
                srcLines.push(
                  `// ${ds.name} — PlanetScale (server-side only)`,
                  `// import { connect } from '@planetscale/database';`,
                  `// const conn = connect({ host: process.env.DATABASE_HOST, username: process.env.DATABASE_USERNAME, password: process.env.DATABASE_PASSWORD });`,
                  '',
                );
              }
            }

            // DB-B FIX: Same pattern as .env.local above — always write so that
            // removing all data sources clears the generated file rather than
            // leaving stale fetch functions that reference deleted sources.
            if (srcLines.length > 2) {
              await writeFile(sourcesPath, srcLines.join('\n'));
            } else {
              // No sources remain — write a minimal stub so imports don't break.
              await writeFile(sourcesPath,
                '// data/sources.ts — auto-generated by Vectra. Do not edit.\n' +
                '// No data sources configured. Add a source in the Data panel.\n'
              );
            }

            prevDataSourcesRef.current = dsKey;
            console.log(`[Vectra] Data sources synced → .env.local, ${sourcesPath}`);
          }
        }

        // Advance the prev-ref checkpoint
        prevElementsRef.current = elements;

      } catch (e) {
        console.error('[useFileSync] Sync error:', e);
      } finally {
        isSyncing.current = false;
        // UX-28 [PERMANENT]: Signal save complete regardless of success/error.
        window.dispatchEvent(new CustomEvent('vectra:save-state', { detail: { saving: false } }));
      }
    };

    // PERF-3: Mirror global AI flag into ref each effect cycle.
    isAIRunning.current = !!(window as any).__vectra_ai_running;

    // PERF-3: If AI just finished and a forced sync was armed, fire immediately.
    if (!isAIRunning.current && syncForcedAfterAI.current) {
      syncForcedAfterAI.current = false;
      const timer = setTimeout(sync, 0);
      return () => clearTimeout(timer);
    }

    // S-2 FIX: smart debounce — delay varies by change type to prevent starvation.
    //
    //   AI running      → hold at 1000ms, force-sync when AI finishes (PERF-3)
    //   AI generation   → node count changes rapidly → 800ms (let it settle)
    //   Structural edit → children[] or type changed → 600ms (standard structural)
    //   Style edit only → same nodes, same count    → 250ms (fast for sliders)
    const prevNodeCount = prevElementsRef.current ? Object.keys(prevElementsRef.current).length : 0;
    const currNodeCount = Object.keys(elements).length;
    const nodeCountChanged = currNodeCount !== prevNodeCount;

    let debounceMs: number;
    if (isAIRunning.current) {
      // PERF-3: AI is actively generating — clamp at 1000ms and arm forced-sync.
      syncForcedAfterAI.current = true;
      debounceMs = 1000;
    } else if (nodeCountChanged) {
      debounceMs = 800;
    } else if (elements !== prevElementsRef.current) {
      debounceMs = 250;
    } else {
      debounceMs = 600;
    }

    const timer = setTimeout(sync, debounceMs);
    return () => clearTimeout(timer);

  }, [elements, pages, apiRoutes, dataSources, framework, status, instance, writeFile, removeFile, theme]); // interaction removed — read via interactionRef
};
