import { useState } from 'react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { useEditor } from '../context/EditorContext';
import { useContainer } from '../context/ContainerContext';
import { generateCode, copyToClipboard, generateNextProjectCode, generateProjectCode, generateGridPage } from '../utils/codeGenerator';
import { INITIAL_DATA, STORAGE_KEY } from '../data/constants';
import {
    Play, Undo, Redo, Code, Grid,
    Check, X, Copy, Trash2,
    Layers, Palette, RotateCcw, Home, Wand2, Download, Loader2, PackageCheck,
    Cpu,
} from 'lucide-react';

import { cn } from '../lib/utils';

// ─── DESIGN TOKEN GENERATOR ───────────────────────────────────────────────────────
// Converts the active project’s GlobalTheme to a tokens.css string that is
// injected into the exported ZIP. Custom property names match :root in
// globals.css (fileSystemTemplates.ts) so the exported project is consistent.
// Pure function — no side effects, no imports needed.

const buildTokensCSS = (theme: {
    primary: string;
    secondary: string;
    accent: string;
    radius: string;
    font: string;
}): string => {
    const now = new Date().toISOString();
    const fontEncoded = encodeURIComponent(theme.font).replace(/%20/g, '+');
    return [
        `/**`,
        ` * tokens.css — Design Tokens`,
        ` *`,
        ` * Auto-generated by Vectra Visual Builder.`,
        ` * Generated: ${now}`,
        ` *`,
        ` * CSS custom properties map to Tailwind config in tailwind.config.js`,
        ` * (theme.extend.colors / borderRadius / fontFamily).`,
        ` *`,
        ` * Usage:`,
        ` *   background-color: var(--primary);   → bg-primary (Tailwind)`,
        ` *   color: var(--secondary);             → text-secondary (Tailwind)`,
        ` *   border-color: var(--accent);         → border-accent (Tailwind)`,
        ` *   border-radius: var(--radius);        → rounded (Tailwind default)`,
        ` *   font-family: var(--font-sans);       → font-sans (Tailwind)`,
        ` *`,
        ` * Do not edit directly — regenerate by exporting from Vectra.`,
        ` */`,
        ``,
        `:root {`,
        `  /* ── Brand Colors ────────────────────────────────────────────── */`,
        `  --primary:   ${theme.primary};   /* Tailwind: bg-primary / text-primary     */`,
        `  --secondary: ${theme.secondary}; /* Tailwind: bg-secondary / text-secondary */`,
        `  --accent:    ${theme.accent};    /* Tailwind: bg-accent / text-accent       */`,
        ``,
        `  /* ── Shape ───────────────────────────────────────────────────── */`,
        `  --radius: ${theme.radius};       /* Tailwind: rounded (default border-radius) */`,
        ``,
        `  /* ── Typography ─────────────────────────────────────────────── */`,
        `  --font-sans: '${theme.font}', system-ui, -apple-system, sans-serif;`,
        `  /* To load the font, add to your layout.tsx <head>:`,
        `     <link href="https://fonts.googleapis.com/css2?family=${fontEncoded}&display=swap"`,
        `           rel="stylesheet" />                                             */`,
        `}`,
        ``,
        `/* ── Dark mode overrides (uncomment and customise as needed) ─────────────── */`,
        `/*`,
        `@media (prefers-color-scheme: dark) {`,
        `  :root {`,
        `    --primary:   ${theme.primary};`,
        `    --secondary: ${theme.secondary};`,
        `    --accent:    ${theme.accent};`,
        `  }`,
        `}`,
        `*/`,
        ``,
    ].join('\n');
};

export const Header = () => {
    const {
        history, previewMode, setPreviewMode, elements, setElements,
        activePageId, setSelectedId, viewMode, setViewMode, selectedId,
        deleteElement, exitProject, setMagicBarOpen,
        pages, dataSources, framework,
        theme,  // Direction 2: needed by buildTokensCSS()
    } = useEditor();

    const { instance, status } = useContainer();
    const [showCode, setShowCode] = useState(false);
    const [code, setCode] = useState('');
    const [copied, setCopied] = useState(false);
    const [isExporting, setIsExporting] = useState(false);
    const [exportDone, setExportDone] = useState(false);
    // ── Phase F2: Grid converter state ──────────────────────────────────────
    // ── Item 3: Multi-page grid results ─────────────────────────────────────────
    interface GridPageResult {
        code: string;
        error: string | null;
        layout: import('../utils/codeGenerator').GridLayout | null;
    }

    // Map<pageId, GridPageResult> — keyed by page.id
    const [gridPageResults, setGridPageResults] = useState<Map<string, GridPageResult>>(new Map());
    const [gridSelectedPageId, setGridSelectedPageId] = useState<string>('');

    // KEEP these existing state vars:
    const [showGridCode, setShowGridCode] = useState(false);
    const [gridCopied, setGridCopied] = useState(false);
    const [isConvertingGrid, setIsConvertingGrid] = useState(false);
    const [useFrUnits, setUseFrUnits] = useState(false);

    const handleGenerate = () => {
        // HYBRID GENERATION: Try Rust first, then fallback to TS
        let generated = "";

        if ((window as any).vectraWasm) {
            try {
                generated = (window as any).vectraWasm.generate_react_code(elements, activePageId);
                console.log("Code generated using Rust Engine");
            } catch (e) {
                console.warn("Rust export failed, falling back to TS", e);
                generated = generateCode(elements, activePageId);
            }
        } else {
            generated = generateCode(elements, activePageId);
        }

        setCode(generated);
        setShowCode(true);
        setCopied(false);
    };

    const handleCopy = async () => {
        const success = await copyToClipboard(code);
        if (success) { setCopied(true); setTimeout(() => setCopied(false), 2000); }
    };

    const togglePreview = () => {
        if (!previewMode) setSelectedId(null);
        setPreviewMode(!previewMode);
    };

    const handleReset = () => {
        if (confirm('Reset project to default? This will clear all changes.')) {
            setElements(INITIAL_DATA);
            localStorage.removeItem(STORAGE_KEY);
            window.location.reload();
        }
    };

    // ── Item 3: Multi-page grid converter ────────────────────────────────────────
    // Iterates over all pages, runs WASM + generateGridPage() per page.
    // A per-page failure stores an error result without aborting other pages.
    // The modal tab bar lets the user review each page's output independently.
    const handleConvertToGrid = () => {
        if (!(window as any).vectraWasm?.absolute_to_grid) {
            // Surface the WASM error as a single result for all pages
            const errorResult: GridPageResult = {
                code: '',
                error: 'Rust WASM engine is not loaded.\n\nCompile the engine first:\n  cd vectra-engine && wasm-pack build --target web',
                layout: null,
            };
            const results = new Map<string, GridPageResult>();
            pages.forEach(p => results.set(p.id, errorResult));
            setGridPageResults(results);
            setGridSelectedPageId(pages[0]?.id || '');
            setShowGridCode(true);
            return;
        }

        setIsConvertingGrid(true);
        setGridPageResults(new Map());

        const px = (val: unknown): number => {
            const n = parseFloat(String(val || 0));
            return isNaN(n) ? 0 : n;
        };

        const results = new Map<string, GridPageResult>();
        let firstPageId = '';

        for (const page of pages) {
            if (!firstPageId) firstPageId = page.id;

            try {
                const pageRoot = elements[page.rootId];
                const canvasFrameId = pageRoot?.children?.find(
                    (cid: string) => elements[cid]?.type === 'webpage'
                ) || pageRoot?.children?.[0];

                if (!canvasFrameId) {
                    results.set(page.id, {
                        code: '', error: `No canvas frame found on page "${page.name}".`, layout: null,
                    });
                    continue;
                }

                const canvasFrame = elements[canvasFrameId];
                const childIds: string[] = canvasFrame?.children || [];

                if (childIds.length === 0) {
                    results.set(page.id, {
                        code: '', error: `Page "${page.name}" has no canvas children to convert.`, layout: null,
                    });
                    continue;
                }

                const gridNodes = childIds
                    .map(id => {
                        const node = elements[id];
                        if (!node) return null;
                        const style = (node.props?.style as any) || {};
                        return { id, x: px(style.left), y: px(style.top), w: px(style.width), h: px(style.height) };
                    })
                    .filter((n): n is NonNullable<typeof n> => n !== null && n.w > 0 && n.h > 0);

                if (gridNodes.length === 0) {
                    results.set(page.id, {
                        code: '',
                        error: `No nodes with valid dimensions on page "${page.name}".\nMake sure canvas children have explicit width/height.`,
                        layout: null,
                    });
                    continue;
                }

                const canvasWidth = px((canvasFrame.props?.style as any)?.width) || 1440;
                const resultJson: string = (window as any).vectraWasm.absolute_to_grid(
                    JSON.stringify(gridNodes),
                    canvasWidth
                );
                const gridLayout = JSON.parse(resultJson);
                const generated = generateGridPage(
                    page, elements, gridLayout,
                    framework as 'nextjs' | 'vite',
                    useFrUnits
                );

                results.set(page.id, { code: generated, error: null, layout: gridLayout });

                console.log(
                    `[Vectra] ✅ Grid: "${page.name}" — ` +
                    `${gridLayout.templateColumns.split(' ').length} cols × ` +
                    `${gridLayout.templateRows.split(' ').length} rows`
                );
            } catch (err) {
                const msg = err instanceof Error ? err.message : String(err);
                console.error(`[Vectra] Grid conversion failed for page "${page.name}":`, err);
                results.set(page.id, { code: '', error: msg, layout: null });
            }
        }

        setGridPageResults(results);
        setGridSelectedPageId(firstPageId);
        setUseFrUnits(false);
        setShowGridCode(true);
        setGridCopied(false);
        setIsConvertingGrid(false);
    };

    // ─── Sprint 1 / Item 3: fr/px unit toggle ─────────────────────────────────
    // Regenerate all pages that have a valid layout
    const handleFrToggle = () => {
        const nextFr = !useFrUnits;
        setUseFrUnits(nextFr);
        setGridCopied(false);

        // Regenerate all pages that have a valid layout (no WASM re-call)
        setGridPageResults(prev => {
            const updated = new Map(prev);
            for (const page of pages) {
                const result = prev.get(page.id);
                if (!result?.layout) continue; // skip pages with errors
                const regenerated = generateGridPage(
                    page, elements, result.layout,
                    framework as 'nextjs' | 'vite',
                    nextFr
                );
                updated.set(page.id, { ...result, code: regenerated });
            }
            return updated;
        });
    }; // reset — code changed

    const handleExportZip = async () => {
        if (!instance || status !== 'ready') {
            alert('Virtual File System is still booting. Please wait a moment.');
            return;
        }

        setIsExporting(true);
        setExportDone(false);

        try {
            // ── PRE-EXPORT FLUSH ───────────────────────────────────────────────
            // Generate and write all page/layout files directly before reading VFS.
            // This guarantees the ZIP has the latest state even if useFileSync's
            // 600ms debounce hasn't fired yet.
            try {
                if (framework === 'nextjs') {
                    const { files } = generateNextProjectCode(elements, pages, dataSources || []);
                    for (const [path, content] of Object.entries(files)) {
                        await instance.fs.writeFile(path, content).catch(() => { });
                    }
                } else {
                    const { files } = generateProjectCode(elements, pages, dataSources || []);
                    for (const [path, content] of Object.entries(files)) {
                        await instance.fs.writeFile(path, content).catch(() => { });
                    }
                }
                console.log('[Vectra] Pre-export flush complete.');
            } catch (flushErr) {
                console.warn('[Vectra] Pre-export flush warn (non-fatal):', flushErr);
            }

            const zip = new JSZip();

            // ── Sprint 3 (Item 3): Multi-page grid injection ──────────────────────────
            // Write every successfully converted page into the grid/ folder.
            // Pages with errors are skipped — their slots are not written.
            if (gridPageResults.size > 0) {
                const gridFolder = zip.folder('grid');
                let injectedCount = 0;

                for (const page of pages) {
                    const result = gridPageResults.get(page.id);
                    if (!result?.code || result.error) continue;

                    const pageName = page.name.replace(/[^a-zA-Z0-9]/g, '');
                    const unitType = useFrUnits ? 'fr (fluid)' : 'px (fixed)';
                    const layout = result.layout;
                    const colCount = layout?.templateColumns.split(' ').length ?? '?';
                    const rowCount = layout?.templateRows.split(' ').length ?? '?';

                    gridFolder!.file(`${pageName}Grid.tsx`, result.code);
                    injectedCount++;
                    console.log(`[Vectra] 📐 Grid → grid/${pageName}Grid.tsx (${colCount}×${rowCount}, ${unitType})`);
                }

                if (injectedCount > 0) {
                    const readme = [
                        `# Grid Layouts`,
                        ``,
                        `Auto-generated by Vectra "Convert to Grid" (Phase F2 / Item 3).`,
                        ``,
                        `## Files`,
                        ...pages
                            .filter(p => gridPageResults.get(p.id)?.code && !gridPageResults.get(p.id)?.error)
                            .map(p => {
                                const name = p.name.replace(/[^a-zA-Z0-9]/g, '');
                                const layout = gridPageResults.get(p.id)?.layout;
                                const cols = layout?.templateColumns.split(' ').length ?? '?';
                                const rows = layout?.templateRows.split(' ').length ?? '?';
                                return `- \`${name}Grid.tsx\` — page "${p.name}", ${cols} cols × ${rows} rows`;
                            }),
                        ``,
                        `## Unit mode`,
                        `${useFrUnits ? 'fr units (fluid — tracks scale with container width)' : 'px units (fixed — tracks match original canvas pixel dimensions)'}`,
                        ``,
                        `## Usage`,
                        `Replace the corresponding \`app/[slug]/page.tsx\` with each Grid file,`,
                        `or copy the grid layout styles into your existing page components.`,
                        ``,
                        `Generated: ${new Date().toISOString()}`,
                        `Framework: ${framework === 'nextjs' ? 'Next.js 14 App Router' : 'Vite + React'}`,
                    ].join('\n');

                    gridFolder!.file('README.md', readme);
                }
            }
            // ── End Sprint 3 / Item 3 ─────────────────────────────────────────────────

            // ── Direction 2: Design token injection ───────────────────────────────
            // tokens.css is written to the ZIP root, NOT to the VFS, so it
            // has zero impact on the running dev server or Tailwind’s JIT.
            // The developer can import it in app/globals.css or layout.tsx.
            const tokensContent = buildTokensCSS(theme);
            zip.file('tokens.css', tokensContent);
            console.log('[Vectra] 🎨 Design tokens injected: tokens.css');
            // ── End Direction 2 ───────────────────────────────────────────────

            // Recursively read VFS directory → populate zip
            const addDir = async (dirPath: string, zipFolder: JSZip) => {
                const entries = await instance.fs.readdir(dirPath, { withFileTypes: true });

                for (const entry of entries) {
                    // Skip heavy / irrelevant dirs
                    if (['node_modules', '.git', '.vite', 'dist', '.next'].includes(entry.name)) continue;

                    const fullPath = dirPath === '/'
                        ? `/${entry.name}`
                        : `${dirPath}/${entry.name}`;

                    if (entry.isDirectory()) {
                        await addDir(fullPath, zipFolder.folder(entry.name)!);
                    } else {
                        const content = await instance.fs.readFile(fullPath, 'utf-8');
                        zipFolder.file(entry.name, content);
                    }
                }
            };

            const projectName = framework === 'nextjs' ? 'vectra-nextjs' : 'vectra-vite';
            console.log(`[Vectra] 📦 Building ${projectName} ZIP from VFS...`);
            await addDir('/', zip);

            const blob = await zip.generateAsync({
                type: 'blob',
                compression: 'DEFLATE',
                compressionOptions: { level: 6 },
            });

            saveAs(blob, `${projectName}-project.zip`);
            console.log(`[Vectra] ✅ ${projectName}-project.zip downloaded!`);

            // Show green checkmark briefly
            setExportDone(true);
            setTimeout(() => setExportDone(false), 3000);

        } catch (err) {
            console.error('[Vectra] ❌ Export failed:', err);
            alert(`Export failed: ${(err as Error).message}\n\nCheck the browser console for details.`);
        } finally {
            setIsExporting(false);
        }
    };

    return (
        <>
            {/* TOP BAR: VS Code Theme Match (#333333) */}
            <div className="h-[50px] bg-[#333333] border-b border-[#252526] flex items-center justify-between px-4 shrink-0 z-50 text-[#cccccc]">

                {/* LEFT: Branding & Reset */}
                <div className="flex items-center gap-4">
                    {/* NEW HOME BUTTON */}
                    <button
                        onClick={exitProject}
                        className="p-2 hover:bg-[#3e3e42] rounded text-[#858585] hover:text-white transition-colors"
                        title="Back to Dashboard"
                    >
                        <Home size={16} />
                    </button>

                    <div className="flex items-center gap-2">
                        <svg width="32" height="32" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <rect x="0" y="0" width="40" height="40" rx="10" fill="#a5b4fc" />
                            <svg x="6" y="6" width="28" height="28" viewBox="0 0 24 24">
                                <path d="M5 6L12 20" stroke="#1e1b4b" strokeWidth="2.5" strokeLinecap="round" strokeDasharray="3 3" />
                                <path d="M12 20L19 6" stroke="#1e1b4b" strokeWidth="2.5" strokeLinecap="round" />
                                <circle cx="5" cy="6" r="1.5" fill="#1e1b4b" />
                                <circle cx="19" cy="6" r="1.5" fill="#1e1b4b" />
                                <rect x="10.5" y="18.5" width="3" height="3" fill="#1e1b4b" />
                            </svg>
                        </svg>
                        <div className="flex flex-col justify-center">
                            <span className="text-sm font-bold text-[#cccccc]">Vectra Project</span>
                        </div>
                    </div>

                    {/* Reset Action */}
                    <button
                        onClick={handleReset}
                        className="flex items-center gap-1.5 px-2 py-1 text-[10px] font-medium text-[#858585] hover:text-[#cccccc] hover:bg-[#3e3e42] rounded transition-colors"
                        title="Reset to factory settings"
                    >
                        <RotateCcw size={10} /> Reset
                    </button>

                    {/* Phase E: Framework Badge */}
                    <div className={`flex items-center gap-1.5 px-2 py-1 rounded border text-[10px] font-bold ${framework === 'nextjs'
                        ? 'bg-white/5 border-white/10 text-[#999]'
                        : 'bg-blue-500/10 border-blue-500/20 text-blue-400'
                        }`}>
                        {framework === 'nextjs' ? <Cpu size={10} /> : <Code size={10} />}
                        {framework === 'nextjs' ? 'Next.js 14' : 'Vite + React'}
                    </div>
                </div>

                {/* CENTER: View Switcher & Device Toggles */}
                <div className="absolute left-1/2 -translate-x-1/2 flex items-center gap-4">

                    {/* View Mode (Layout | Design)  */}
                    <div className="flex items-center bg-[#252526] rounded-md p-0.5 border border-[#3e3e42]">
                        <button
                            onClick={() => setViewMode('skeleton')}
                            className={cn(
                                "flex items-center gap-1.5 px-2.5 py-1 rounded-sm text-[10px] font-medium transition-all",
                                viewMode === 'skeleton' ? "bg-[#3e3e42] text-white shadow-sm" : "text-[#858585] hover:text-[#cccccc]"
                            )}
                        >
                            <Layers size={12} /> Layout
                        </button>
                        <button
                            onClick={() => setViewMode('visual')}
                            className={cn(
                                "flex items-center gap-1.5 px-2.5 py-1 rounded-sm text-[10px] font-medium transition-all",
                                viewMode === 'visual' ? "bg-[#3e3e42] text-white shadow-sm" : "text-[#858585] hover:text-[#cccccc]"
                            )}
                        >
                            <Palette size={12} /> Design
                        </button>
                    </div>
                </div>

                {/* RIGHT: Actions */}
                <div className="flex items-center gap-2">
                    {/* History */}
                    <div className="flex items-center gap-0.5 opacity-80">
                        <button onClick={history.undo} className="p-2 hover:bg-[#3e3e42] hover:text-white rounded text-[#858585] transition-colors" title="Undo"><Undo size={14} /></button>
                        <button onClick={history.redo} className="p-2 hover:bg-[#3e3e42] hover:text-white rounded text-[#858585] transition-colors" title="Redo"><Redo size={14} /></button>
                    </div>

                    {/* AI Magic Bar Toggle */}
                    <button
                        onClick={() => setMagicBarOpen(true)}
                        className="flex items-center gap-2 px-3 py-1.5 bg-gradient-to-r from-[#7c3aed] to-[#2563eb] text-white rounded text-[10px] font-black hover:shadow-lg transition-all border border-white/10 group active:scale-95"
                    >
                        <Wand2 size={12} className="group-hover:rotate-12 transition-transform" />
                        <span className="hidden lg:inline uppercase tracking-tight">Ask AI</span>
                        <span className="text-[8px] opacity-40 font-mono hidden xl:inline border border-white/20 px-1 rounded ml-1 group-hover:opacity-100">⌘K</span>
                    </button>

                    <div className="h-4 w-px bg-[#3e3e42] mx-1" />


                    {/* Delete Button */}
                    <button
                        onClick={() => {
                            if (selectedId && !['application-root', 'page-home', 'main-canvas'].includes(selectedId)) {
                                deleteElement(selectedId);
                            }
                        }}
                        disabled={!selectedId || ['application-root', 'page-home', 'main-canvas'].includes(selectedId)}
                        className={cn(
                            "p-2 rounded transition-colors",
                            (selectedId && !['application-root', 'page-home', 'main-canvas'].includes(selectedId))
                                ? "text-[#858585] hover:text-red-400 hover:bg-[#3e3e42]"
                                : "text-[#555] cursor-not-allowed"
                        )}
                        title="Delete Selected (Del)"
                    >
                        <Trash2 size={14} />
                    </button>

                    <div className="h-4 w-px bg-[#3e3e42] mx-2" />

                    {/* Export Code */}
                    <button onClick={handleGenerate} className="p-2 text-[#858585] hover:text-white hover:bg-[#3e3e42] rounded transition-colors" title="Export Code">
                        <Code size={16} />
                    </button>

                    {/* ── Phase F2: Convert to Grid ──────────────────────────────── */}
                    <button
                        id="convert-to-grid-btn"
                        onClick={handleConvertToGrid}
                        disabled={isConvertingGrid || !(window as any).vectraWasm?.absolute_to_grid}
                        title={
                            !(window as any).vectraWasm?.absolute_to_grid
                                ? 'WASM engine not loaded — run: cd vectra-engine && wasm-pack build --target web'
                                : 'Convert canvas layout to responsive CSS Grid'
                        }
                        className={cn(
                            'flex items-center gap-1.5 px-2 py-1.5 rounded text-[10px] font-bold transition-all border',
                            isConvertingGrid
                                ? 'bg-[#252526] border-[#3e3e42] text-purple-400 cursor-wait'
                                : 'bg-[#252526] border-[#3e3e42] text-[#858585] hover:text-purple-400 hover:border-purple-500/40 disabled:opacity-30 disabled:cursor-not-allowed'
                        )}
                    >
                        {isConvertingGrid
                            ? <><Loader2 size={11} className="animate-spin" /><span>Converting...</span></>
                            : <><Grid size={11} /><span>To Grid</span></>
                        }
                    </button>

                    {/* ── Download ZIP Button ────────────────────────────── */}
                    <button
                        onClick={handleExportZip}
                        disabled={isExporting || status !== 'ready'}
                        title={status !== 'ready' ? 'Waiting for VFS...' : 'Download production-ready ZIP'}
                        className={cn(
                            'flex items-center gap-1.5 px-2.5 py-1.5 rounded text-xs font-bold transition-all border',
                            exportDone
                                ? 'bg-green-500/20 border-green-500/50 text-green-400'
                                : isExporting
                                    ? 'bg-[#252526] border-[#3e3e42] text-blue-400 cursor-wait'
                                    : 'bg-[#252526] border-[#3e3e42] text-[#858585] hover:text-white hover:border-[#007acc] disabled:opacity-40 disabled:cursor-not-allowed'
                        )}
                    >
                        {isExporting ? (
                            <><Loader2 size={12} className="animate-spin" /><span>Zipping...</span></>
                        ) : exportDone ? (
                            <><PackageCheck size={12} /><span>Downloaded!</span></>
                        ) : (
                            <><Download size={12} /><span>Export ZIP</span></>
                        )}
                    </button>

                    <div className="h-4 w-px bg-[#3e3e42] mx-2" />

                    {/* WebContainer Status Indicator */}
                    <div className="flex items-center gap-2 mr-2">
                        <span className={`w-2 h-2 rounded-full ${status === 'ready' ? 'bg-green-500 shadow-[0_0_8px_rgba(34,197,94,0.5)]' : 'bg-yellow-500 animate-pulse'}`} />
                        <span className="text-xs text-zinc-500 font-mono uppercase tracking-wider">
                            {status === 'ready' ? 'Ready' : 'Building...'}
                        </span>
                    </div>

                    {/* Preview Button (Primary Action) */}
                    <button
                        onClick={togglePreview}
                        className={cn(
                            "flex items-center gap-2 px-3 py-1.5 rounded text-xs font-bold transition-all",
                            previewMode
                                ? 'bg-[#007acc] text-white hover:bg-[#0063a5] shadow-sm'
                                : 'bg-[#252526] text-[#cccccc] border border-[#3e3e42] hover:border-[#007acc] hover:text-[#007acc]'
                        )}
                    >
                        <Play size={10} fill={previewMode ? "currentColor" : "none"} />
                        {previewMode ? 'Running' : 'Preview'}
                    </button>
                </div>
            </div >

            {/* Code Modal (Dark Theme Adapted) */}
            {
                showCode && (
                    <div className="fixed inset-0 bg-black/80 z-[100] flex items-center justify-center p-8 backdrop-blur-sm animate-fade-in">
                        <div className="bg-[#1e1e1e] w-full max-w-5xl h-[85vh] rounded-xl shadow-2xl flex flex-col overflow-hidden border border-[#333]">
                            <div className="flex justify-between items-center p-4 border-b border-[#333] bg-[#252526]">
                                <span className="font-medium text-gray-200 flex items-center gap-2">
                                    <Code size={16} className="text-[#007acc]" /> Generated React Code
                                </span>
                                <div className="flex gap-2">
                                    <button onClick={handleCopy} className="px-3 py-1.5 bg-[#007acc] hover:bg-[#0063a5] text-white text-xs font-bold rounded flex items-center gap-2 transition-colors">
                                        {copied ? <Check size={12} /> : <Copy size={12} />} {copied ? 'Copied!' : 'Copy'}
                                    </button>
                                    <button onClick={() => setShowCode(false)} className="p-1.5 hover:bg-[#3e3e42] rounded transition-colors">
                                        <X size={18} className="text-[#858585] hover:text-white" />
                                    </button>
                                </div>
                            </div>
                            <div className="flex-1 overflow-auto p-6 bg-[#1e1e1e]">
                                <pre className="text-[13px] font-mono text-[#d4d4d4] leading-relaxed whitespace-pre-wrap"><code>{code}</code></pre>
                            </div>
                        </div>
                    </div>
                )
            }

            {/* ── Item 3: Multi-page Grid Code Modal ─────────────────────────────── */}
            {showGridCode && (
                <div className="fixed inset-0 bg-black/80 z-[100] flex items-center justify-center p-8 backdrop-blur-sm">
                    <div className="bg-[#1e1e1e] w-full max-w-5xl h-[85vh] rounded-xl shadow-2xl flex flex-col overflow-hidden border border-[#333]">

                        {/* Modal header */}
                        <div className="flex items-center gap-3 px-4 py-3 border-b border-[#333] bg-[#252526] flex-wrap">
                            <span className="font-medium text-gray-200 flex items-center gap-2 shrink-0">
                                <Grid size={16} className="text-purple-400" />
                                Responsive CSS Grid
                            </span>

                            {/* Page tab bar */}
                            {pages.length > 1 && (
                                <div className="flex items-center gap-1 flex-1 flex-wrap">
                                    {pages.map(page => {
                                        const result = gridPageResults.get(page.id);
                                        const isActive = page.id === gridSelectedPageId;
                                        const hasError = !!result?.error;
                                        return (
                                            <button
                                                key={page.id}
                                                onClick={() => { setGridSelectedPageId(page.id); setGridCopied(false); }}
                                                className={cn(
                                                    'px-2.5 py-1 rounded text-[10px] font-bold transition-all border',
                                                    isActive
                                                        ? hasError
                                                            ? 'bg-red-500/15 border-red-500/30 text-red-400'
                                                            : 'bg-purple-500/15 border-purple-500/30 text-purple-300'
                                                        : 'bg-transparent border-transparent text-[#555] hover:text-[#888]'
                                                )}
                                            >
                                                {hasError ? '⚠ ' : ''}{page.name}
                                            </button>
                                        );
                                    })}
                                </div>
                            )}

                            {/* fr/px toggle */}
                            {(() => {
                                const hasAnyLayout = [...gridPageResults.values()].some(r => r.layout !== null);
                                return hasAnyLayout && (
                                    <button
                                        onClick={handleFrToggle}
                                        title={useFrUnits ? 'Switch to px' : 'Switch to fr (fluid)'}
                                        className={cn(
                                            'flex items-center gap-1.5 px-2.5 py-1.5 rounded text-[10px] font-bold border transition-all shrink-0',
                                            useFrUnits
                                                ? 'bg-purple-500/20 border-purple-500/40 text-purple-300'
                                                : 'bg-[#2d2d2d] border-[#3e3e42] text-[#666] hover:text-[#999]'
                                        )}
                                    >
                                        <span className={cn(
                                            'w-6 h-3 rounded-full flex items-center transition-colors px-0.5',
                                            useFrUnits ? 'bg-purple-500 justify-end' : 'bg-[#444] justify-start'
                                        )}>
                                            <span className="w-2 h-2 rounded-full bg-white shadow-sm" />
                                        </span>
                                        {useFrUnits ? 'fr units' : 'px units'}
                                    </button>
                                );
                            })()}

                            {/* Copy button */}
                            {(() => {
                                const activeResult = gridPageResults.get(gridSelectedPageId);
                                return activeResult?.code && (
                                    <button
                                        onClick={async () => {
                                            const ok = await copyToClipboard(activeResult.code);
                                            if (ok) { setGridCopied(true); setTimeout(() => setGridCopied(false), 2000); }
                                        }}
                                        className="px-3 py-1.5 bg-purple-600 hover:bg-purple-700 text-white text-xs font-bold rounded flex items-center gap-2 transition-colors shrink-0"
                                    >
                                        {gridCopied ? <><Check size={12} />Copied!</> : <><Copy size={12} />Copy</>}
                                    </button>
                                );
                            })()}

                            <button
                                onClick={() => { setShowGridCode(false); setGridPageResults(new Map()); }}
                                className="p-1.5 hover:bg-[#3e3e42] rounded text-gray-400 transition-colors shrink-0 ml-auto"
                            >
                                <X size={16} />
                            </button>
                        </div>

                        {/* Modal body — show selected page result */}
                        <div className="flex-1 overflow-auto">
                            {(() => {
                                const activeResult = gridPageResults.get(gridSelectedPageId);
                                const activePage = pages.find(p => p.id === gridSelectedPageId);

                                if (!activeResult) {
                                    return (
                                        <div className="flex items-center justify-center h-full text-[#555] text-sm">
                                            No results yet.
                                        </div>
                                    );
                                }

                                if (activeResult.error) {
                                    return (
                                        <div className="p-6">
                                            <div className="bg-red-500/5 border border-red-500/20 rounded-lg p-4 mb-4">
                                                <p className="text-red-400 text-xs font-bold mb-2 flex items-center gap-2">
                                                    <X size={12} /> Conversion failed — {activePage?.name}
                                                </p>
                                                <pre className="text-red-300/80 text-[11px] font-mono whitespace-pre-wrap leading-relaxed">
                                                    {activeResult.error}
                                                </pre>
                                            </div>
                                            <div className="p-3 bg-[#252526] border border-[#3e3e42] rounded text-[10px] text-[#666] font-mono space-y-1">
                                                <p>Checklist:</p>
                                                <p>• Canvas frame must have children with explicit left/top/width/height</p>
                                                <p>• Elements need position:absolute (canvas layoutMode nodes)</p>
                                                <p>• WASM must be compiled: cd vectra-engine &amp;&amp; wasm-pack build --target web</p>
                                            </div>
                                        </div>
                                    );
                                }

                                return (
                                    <pre className="p-6 text-[#d4d4d4] text-xs font-mono leading-relaxed whitespace-pre overflow-x-auto h-full">
                                        <code>{activeResult.code}</code>
                                    </pre>
                                );
                            })()}
                        </div>

                        {/* Modal footer */}
                        <div className="px-4 py-2 border-t border-[#333] bg-[#1a1a1a] flex items-center gap-3">
                            <span className="text-[10px] text-[#555]">
                                {pages.length > 1
                                    ? `${[...gridPageResults.values()].filter(r => !r.error).length} of ${pages.length} pages converted successfully`
                                    : 'Replace app/page.tsx with this file, or use as a starting point.'}
                            </span>
                            <span className="ml-auto text-[9px] text-[#444] font-mono">
                                Phase F2 — Rust WASM Grid Engine
                            </span>
                        </div>
                    </div>
                </div>
            )}
        </>
    );
};
